### ISSUE TITLE
Make summary script work only with subset of tools

### ISSUE THREAD

**Issue by denisbeslic** [denisbeslic/denovopipeline#3]

**Comment by BenSamy2020** [comment]
Greetigns @denisbeslic,

I am a new user to your denovopipeline. Can I confirm with you that, just by using only 2 denovo tools, I would be able to get the summary script work?

Regards,
Ben

**Comment by denisbeslic** [comment]
Dear Ben,

thank you for your interest! Denovopipeline will output an warning/error message that it could not find the results of the other tools. However, the summary file will be sucessfully created using only 2 or 3 tools. Let me know if you encounter problems using only 2 tools.

Best,
Denis
________________________________
Von: Benjamin Samy ***@***.***>
Gesendet: Mittwoch, 14. Dezember 2022 14:13
An: denisbeslic/denovopipeline ***@***.***>
Cc: dbeslic ***@***.***>; Mention ***@***.***>
Betreff: Re: [denisbeslic/denovopipeline] Make summary script work only with subset of tools (Issue #3)


Greetigns @denisbeslic<https://github.com/denisbeslic>,

I am a new user to your denovopipeline. Can I confirm with you that, just by using only 2 denovo tools, I would be able to get the summary script work?

Regards,
Ben
