### ISSUE TITLE
How to process specific enzymes

### ISSUE THREAD

**Issue by hjkimbertis** [denisbeslic/denovopipeline#5]
When I want to process files with other enzymes than trypsin, Should I change the parameters manually?

**Comment by denisbeslic** [comment]
The DL-based de novo sequencing tools (DeepNovo, SMSNet, PointNovo) have no parameters for enzyme specificity. It is recommended to retrain the model based on your enzyme-specific data, but it also works to a certain extend with the base (trypsin) model. 
Novor has no option to choose enzymes other than trypsin. 
pNovo3 has multiple available enzyme parameters available and you should choose the correct one when using the pNovo3 GUI.
If you are performing a database search (f.e. with SearchGUI and PeptideShaker) you should select the specific enzyme.
You don't need to make changes to the denovopipeline commands.

I hope that answers your question.

**Comment by hjkimbertis** [comment]
Thank you for your comment!
